**Алгоритмы анализа данных**

**Урок 8. Снижение размерности данных**

Домашнее задание №8.

1. Обучите любую модель классификации на датасете IRIS до применения PCA и после него. Сравните качество классификации по отложенной выборке.

2. Напишите свою реализацию метода главных компонент посредством сингулярного разложения с использованием функции numpy.linalg.svd().

In [33]:
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

In [79]:
X, y = datasets.load_iris(return_X_y=True)

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [81]:
clf = LogisticRegression(random_state=42).fit(X_test, y_test)

In [82]:
clf.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [83]:
clf.predict_proba(X_test[:2, :])

array([[1.63940405e-02, 7.68754222e-01, 2.14851738e-01],
       [9.30888638e-01, 6.91012340e-02, 1.01276607e-05]])

In [84]:
clf.score(X_train, y_train)

0.95

In [85]:
pca = PCA(n_components=2)

In [86]:
pca.fit(X)

PCA(n_components=2)

In [87]:
print(pca.explained_variance_ratio_)

[0.92461872 0.05306648]


In [88]:
print(pca.singular_values_)

[25.09996044  6.01314738]


In [89]:
X_pca = pca.fit_transform(X)

In [90]:
X.shape

(150, 4)

In [91]:
X_pca.shape

(150, 2)

In [92]:
X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(X_pca, y, test_size=0.33, random_state=42)

In [93]:
clf_pca = LogisticRegression(random_state=42).fit(X_test_pca, y_test_pca)

In [94]:
clf_pca.predict(X_test_pca)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [97]:
clf_pca.predict_proba(X_test_pca[:2,:])

array([[1.78617332e-02, 7.06905230e-01, 2.75233037e-01],
       [9.35582899e-01, 6.44103064e-02, 6.79474338e-06]])

In [98]:
clf_pca.score(X_train_pca, y_train_pca)

0.92

In [122]:
def own_func_with_svd(X, dd):
    xt = X.T
    xt_x = xt.dot(X)
    
    svd = np.linalg.svd(xt_x)[0]
    u = svd[0]
    d = svd[1]
    vt = svd[2]
    
    w = d
    
    z = X.dot(w) 
    return z
    
#     print(u)
#     print(d)
#     print(vt)
#     print(z)

In [123]:
own_func_with_svd(X, 2)

array([ -4.86083709,  -4.51144761,  -4.47725494,  -4.51962054,
        -4.87750293,  -5.45958495,  -4.64784516,  -4.83567836,
        -4.26673007,  -4.60192078,  -5.15173618,  -4.82718546,
        -4.44171338,  -4.0490973 ,  -5.265221  ,  -5.71193439,
        -5.18948763,  -4.8925627 ,  -5.48721075,  -5.12411038,
        -5.12276149,  -5.10116154,  -4.45537113,  -5.04923801,
        -5.02975845,  -4.68450489,  -4.9666539 ,  -4.96637004,
        -4.84417126,  -4.67982794,  -4.6631621 ,  -5.05116404,
        -5.26269114,  -5.39559271,  -4.63364639,  -4.52375646,
        -4.94534723,  -4.8077687 ,  -4.25388019,  -4.87368697,
        -4.78702975,  -3.94089326,  -4.36322909,  -5.08477957,
        -5.42593332,  -4.5051646 ,  -5.15990911,  -4.50677066,
        -5.11372756,  -4.71347958,  -8.0279877 ,  -7.69661294,
        -8.10207891,  -6.46139246,  -7.58344809,  -7.14840361,
        -7.88005305,  -5.72016807,  -7.61267995,  -6.53026569,
        -5.67452755,  -7.19464796,  -6.50158428,  -7.52